
steps:
# 1) Install deps & train (opcional: removível se já tiver modelo)
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      pip install --no-cache-dir -r requirements.txt
      python scripts/train.py || true

# 2) Register model version (opcional)
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      pip install --no-cache-dir google-cloud-aiplatform google-cloud-storage
      python scripts/register_model.py || true

# 3) Build API image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/recrutador-api:latest', '.']

# 4) Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/recrutador-api:latest']

# 5) Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - recrutador-api
    - --image=gcr.io/$PROJECT_ID/recrutador-api:latest
    - --region=us-central1
    - --allow-unauthenticated

images:
- gcr.io/$PROJECT_ID/recrutador-api:latest
